### ISSUE TITLE
nbgitpuller link for this repo

### ISSUE THREAD

**Issue by arnavs** [UBC-R-Study-group/intro_r_workshop#11]
[Obsolete]

**Comment by ian-flores** [comment]
@arnavs the dataset comes in a package called `gapminder`. We just need to make sure that the package is installed in both `PIMS` and `UBC` syzygies.

**Comment by arnavs** [comment]
I'm a bit hesitant to ask for an install on the whole server, because it'll probably require some downtime, and we don't need the package after the workshop (right?).

But it looks like `pip install gapminder` works just fine on syzygy, so probably I'll have them do that in the intro.

**Comment by arnavs** [comment]
Also I think we'd still need a link for this repo.

**Comment by ttimbers** [comment]
@arnavs - we have set up the link (see 5th bullet [here](https://github.com/UBC-R-Study-group/intro_r_workshop#introduction-to-r-workshop)) and a [starting notebook](https://github.com/UBC-R-Study-group/intro_r_workshop/blob/master/starting_notebook.ipynb) which you can leave as is, or edit.

**Comment by ttimbers** [comment]
@arnavs - in your session, please use this code to get the students to load the data:

```
library(tidyverse)
gapminder <- read_csv("data/gapminder_data.csv")
```

This is so things will flow nicely with the sessions that follow you. Thanks!

**Comment by arnavs** [comment]
Thanks @ttimbers. I'll close this issue then. And will do r.e. the above.
