### ISSUE TITLE
Advertise

### ISSUE THREAD

**Issue by ttimbers** [UBC-R-Study-group/intro_r_workshop#2]
- Advertise

**Comment by laijasmine** [comment]
Posted to my lab's slack channel as well as the UBC Science Student Facebook page.

Also a general posting:
Introduction to R Workshop - March 8th

Come learn how to use R to load, clean and wrangle as well as visualize your data! This short and hands-on introduction to R workshop is being led, taught and organized by the UBC R Study group.

More info at: https://ubc-r-study-group.github.io/intro_r_workshop/
