### ISSUE TITLE
IntroRWorkshop Instructor Meeting March 6

### ISSUE THREAD

**Issue by travis-m-blimkie** [UBC-R-Study-group/intro_r_workshop#20]
Hello all,

As the R workshop is fast approaching, I think it'd be a good idea for us to spend a bit of time at tomorrow's study group session (March 6th) going over everything in preparation for Friday. If all the instructors could be in attendance that'd be great!
@arnavs @ian-flores @laijasmine @abaghela

Cheers!

**Comment by laijasmine** [comment]
I will be there! Will we meet at the same room and move elsewhere to discuss?

**Comment by arnavs** [comment]
Me too
